#!/usr/bin/env bash

#Invariables
EXIT_NORMAL=0
EXIT_FAILURE=1
TOUCHPAD_ENABLED=0
TOUCHPAD_DISABLED=1

#check synclient
if ! `which synclient > /dev/null 2>&1`;
then
	echo "Cannot find synclient command"
	return ${EXIT_FAILURE}
fi

STATE=`synclient -l | grep TouchpadOff | awk '{print $3}'`
if [ ${STATE} -eq ${TOUCHPAD_ENABLED} ];
then
	synclient TouchpadOff=${TOUCHPAD_DISABLED}
else
	synclient TouchpadOff=${TOUCHPAD_ENABLED}
fi
