#!/bin/bash

# For apt
if type apt > /dev/null 2>&1; then
    sudo apt update && sudo apt upgrade
fi

# For dnf or yum
if type yum > /dev/null 2>&1; then
    sudo yum update
fi

if type dnf > /dev/null 2>&1; then
    sudo dnf update
fi

# For snap
if type snap > /dev/null 2>&1; then
    sudo snap refresh
fi

# For flatpak
if type snap > /dev/null 2>&1; then
    flatpak update
fi

# For cargo-upodate
if cargo install-update --help > /dev/null 2>&1; then
    cargo install-update -a
fi

# For rust
if type rustup > /dev/null 2>&1; then
	rustup update
fi
