#!/bin/bash

# For apt
if type apt > /dev/null 2>&1; then
    sudo apt update && sudo apt upgrade
fi

# For dnf or yum
if type dnf > /dev/null 2>&1; then
    sudo dnf update
elif type yum > /dev/null 2>&1; then
    sudo yum update
fi

# For snap
if type snap > /dev/null 2>&1; then
    sudo snap refresh
fi

# For flatpak
if type flatpak > /dev/null 2>&1; then
    flatpak update
fi

# For cargo-upodate
if cargo install-update --help > /dev/null 2>&1; then
    cargo install-update -a
fi

# For rust
if type rustup > /dev/null 2>&1; then
    rustup update
fi

# For npm
if type ncu > /dev/null 2>&1; then
    NCU_UPDATE=$(ncu -g | grep "npm -g install")
    if [ ! -z "$NCU_UPDATE" ]; then
        sudo $NCU_UPDATE
    fi
fi
